[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
rev  = '3787e5'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'tarama13/syntax-irc.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
