[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = ['tex', 'latex']

# [[plugins]]
# repo = 'gerw/vim-latex-suite'
# on_ft = ['tex', 'latex']

[[plugins]]
repo= 'mopp/AOJ.vim'
depends = ['unite.vim', 'webapi-vim']
on_ft = ['c', 'cpp']
