[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
rev  = '3787e5'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'junegunn/seoul256.vim'
